'''Implementation of classes for various animals and shapes (10 classes each) to learn learn concepts like virtual functions, abstract classes, base class, derive class, interfaces, polymorphism, modularity nad hierarchy in Python.'''

# Modularity
from animals import *
from shapes import *

# Animals -->
animal1 = Dog()
animal1.char()
animal1.eats()
animal1.sound()
animal1.feature()
print("\n")

animal2 = Lion()
animal2.char()
animal2.eats()
animal2.sound()
animal2.feature()
print("\n")

animal3 = Pig()
animal3.char()
animal3.eats()
animal3.sound()
animal3.feature()
print("\n")

animal4 = Panda()
animal4.char()
animal4.eats()
animal4.sound()
animal4.feature()
print("\n")

animal5 = Horse()
animal5.char()
animal5.eats()
animal5.sound()
animal5.feature()
print("\n")

bird1 = Penguin()
bird1.char()
bird1.eats()
bird1.sound()
bird1.feature()
print("\n")

bird2 = Ostrich()
bird2.char()
bird2.eats()
bird2.sound()
bird2.feature()
print("\n")


# Shapes -->
shape1 = Circle()
shape1.dimension()
shape1.set(70)
shape1.perimeter()
shape1.area()
shape1.draw()
print("\n")

shape2 = Ellipse()
shape2.dimension()
shape2.set(100,50)
shape2.perimeter()
shape2.area()
shape2.draw()
print("\n")

shape3 = Triangle()
shape3.dimension()
shape3.set(100, 110, 140)
shape3.perimeter()
shape3.area()
shape3.draw()
print("\n")

shape4 = Square()
shape4.dimension()
shape4.set(130)
shape4.perimeter()
shape4.area()
shape4.draw()
print("\n")

shape5 = Rectangle()
shape5.dimension()
shape5.set(150, 100)
shape5.perimeter()
shape5.area()
shape5.draw()
print("\n")

shape6 = Parallelogram()
shape6.dimension()
shape6.set(150, 100)
shape6.perimeter()
shape6.area()
shape6.draw()
print("\n")

shape7 = Pentagon()
shape7.dimension()
shape7.set(130)
shape7.perimeter()
shape7.area()
shape7.draw()
print("\n")

shape8 = Hexagon()
shape8.dimension()
shape8.set(130)
shape8.perimeter()
shape8.area()
shape8.draw()
print("\n")

shape9 = Cube()
shape9.dimension()
shape9.set(130)
shape9.perimeter()
shape9.area()
shape9.volume()
shape9.draw()
print("\n")

shape10 = Cuboid()
shape10.dimension()
shape10.set(150, 100, 200)
shape10.perimeter()
shape10.area()
shape10.volume()
shape10.draw()
